# Do not edit this file, it is auto-generated using camera_calibration.py.

# Import statements
from numpy import array, float32

"""
Camera properties from the manufacturer
"""
pixel_width = 1280
pixel_height = 720

# focal length in meters
focal_length = 0.0028

"""
Camera properties found using OpenCV
"""
# These are the x and y focal lengths in pixels, they are different
# because the pixels are not perfectly square.
fpx = 1199.762731
fpy = 1263.368285

# These are the (x, y) coordinates of the principal point, i.e. the
# optical center of the image.
ppx = 598.446870
ppy = 345.534594

# These are the radial and tangential distortion coefficients.
distortion_coefficients = array([[ -0.121147, -0.015633, -0.002517, -0.010681, 0.085236 ]])

# This matrix contains the intrinsic camera properties.
matrix = array([[ 1199.763,  598.447,    0.000 ],
                [    0.000,  345.535, -1263.368 ],
                [    0.000,    1.000,    0.000 ]], dtype=float32)

"""
Measured camera properties
"""

# This is the distance, in meters, from the intersection of the
# pitch and yaw rotation axes to the center of the lens.  This value
# was measured with a tape measure.
axes_to_lens = 0.035
