
# Do not edit this file, it is auto-generated using camera_calibration.py.

# Reprojection error in pixels, a measure of calibration quality
# 0.346075635555

# Import statements
from numpy import array, float32

"""
Camera properties from the manufacturer
"""
pixel_width = 1280
pixel_height = 720


"""
Camera properties found using OpenCV
"""

# These are the radial and tangential distortion coefficients.

distortion_coefficients = array([[  -0.147066,   0.079359,  -0.002976,  -0.010400,   0.006427 ]])


# This matrix contains the intrinsic camera properties.

matrix = array([[   1197.072,      0.000,    599.067 ],
                [      0.000,   1261.160,    344.484 ],
                [      0.000,      0.000,      1.000 ]], dtype=float32)


# The mean distance from the centroid of reference point estimates
# to each estimate for 9 photos.
# 0.00388587904796

# The standard deviation of distances from the centroid of
# reference point estimates to each estimate for 9 photos.
# 0.0021746042681

# Vector in meters from the camera's optical center to a
# stationary reference point that is independent of camera
# orientation.  This vector is in terms of the camera's
# coordinate system.

reference_vector = array([ -0.002205,  -0.003917,  -0.033427])
